"$schema" = "https://jj-vcs.github.io/jj/prerelease/config-schema.json"

[fix.tools.ruff_isort]
command = ["ruff", "check", "--select", "I", "--fix", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.ruff]
command = ["ruff", "format", "--preview", "-", "--stdin-filename=$path"]
patterns = ["glob:'**/*.py'"]

[fix.tools.stylua]
command = ["stylua", "-"]
patterns = ["glob:'**/*.lua'"]

[fix.tools.rustfmt]
command = ["rustfmt", "--emit", "stdout", "--edition", "2024"]
patterns = ["glob:'**/*.rs'"]

[fix.tools.hack]
enabled = false
command = ["hack"]
patterns = ["glob:'**/*'"]
